#!/usr/bin/env python3
"""Build the Confluence (Data Center) edition of the sizing tool.

Writes dist/confluence/:
  ocvs-sizer-tool.js      attach to the Confluence page: the whole tool, prices and libraries, no internet needed
  confluence-macro.html   paste into an HTML macro on that page
  preview.html            local preview (open in a browser)

The tool renders inside a shadow root, so Confluence styles and the tool's styles don't affect each other.
Re-run after updating prices (tools/fetch_prices.py) or the page, then re-attach ocvs-sizer-tool.js.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dist", "confluence")
MOUNT_ID = "ocvs-sizer"
BUNDLE = "ocvs-sizer-tool.js"


def read(*p):
    with open(os.path.join(ROOT, *p), encoding="utf-8") as f:
        return f.read()


def between(s, a, b):
    i = s.index(a) + len(a)
    return s[i:s.index(b, i)]


def main():
    html = read("index.html")
    css = between(html, "<style>", "</style>")
    body = between(html, "<body>", "\n<script>\n")
    app = between(html, "\n<script>\n", "\n</script>")

    # CSS: page-level selectors -> the shadow root and the app wrapper
    css = css.replace(':root:not([data-theme="light"])', ":host").replace(':root[data-theme="dark"]', ":host(.dark)")
    css = css.replace(":root", ":host")
    css = re.sub(r"\bbody\.v2\b", ".app.v2", css)
    css = re.sub(r"(^|[}\s])body\{", r"\1.app{", css)
    css += "\n.app{min-height:100%;text-align:left}\n"

    # JS: look things up inside the shadow root; don't touch the Confluence page URL
    app = app.replace("document.getElementById", "ROOT.getElementById")
    app = app.replace("document.querySelectorAll", "ROOT.querySelectorAll")
    app = app.replace("document.body.classList", "APP.classList")
    app = re.sub(r"try \{ history\.replaceState\([^;]*\); \} catch \(e\) \{\}", "", app)
    app = app.replace('new URLSearchParams(location.search).get("view") === "2" ? 2 : 1', "1")

    libs = [read("vendor", "xlsx.full.min.js"), read("vendor", "pptxgen.bundle.js"),
            read("data", "catalog.js"), read("data", "prices.js"), read("js", "data.js"), read("js", "ppt.js")]

    bundle = "/* OCVS Sizing Tool - Confluence edition. Generated by tools/build_confluence.py; do not edit. */\n"
    bundle += "\n;\n".join(libs) + "\n;\n"
    bundle += "(function () {\n"
    bundle += f"  var host = document.getElementById({json.dumps(MOUNT_ID)});\n"
    bundle += "  if (!host) return;\n"
    bundle += "  var ROOT = host.shadowRoot || host.attachShadow({ mode: 'open' });\n"
    bundle += "  ROOT.innerHTML = '<style>' + " + json.dumps(css) + " + '</style><div class=\"app\">' + " + json.dumps(body) + " + '</div>';\n"
    bundle += "  var APP = ROOT.querySelector('.app');\n"
    bundle += app + "\n})();\n"

    macro = f'''<div id="{MOUNT_ID}"><div style="padding:24px;font-family:Arial,sans-serif;color:#6b778c">Loading the VMware sizing tool…</div></div>
<script>
(function () {{
  // Loads {BUNDLE} attached to this page and runs it inline.
  var meta = function (n) {{ var m = document.querySelector('meta[name="' + n + '"]'); return m ? m.content : ""; }};
  var ctx = meta("ajs-context-path"), pageId = meta("ajs-page-id") || (window.AJS && AJS.params && AJS.params.pageId);
  var url = ctx + "/download/attachments/" + pageId + "/{BUNDLE}?api=v2&t=" + Math.floor(Date.now() / 600000);
  fetch(url, {{ credentials: "same-origin" }})
    .then(function (r) {{ if (!r.ok) throw new Error("HTTP " + r.status); return r.text(); }})
    .then(function (code) {{ var s = document.createElement("script"); s.textContent = code; document.body.appendChild(s); }})
    .catch(function (e) {{
      document.getElementById("{MOUNT_ID}").innerHTML = '<div style="padding:20px;border:1px solid #f5c2c0;background:#fdecea;border-radius:10px;font-family:Arial,sans-serif;color:#8a1c14">' +
        'Could not load the sizing tool (' + e.message + '). Check that <b>{BUNDLE}</b> is attached to this page.</div>';
    }});
}})();
</script>
'''
    preview = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Confluence preview</title>
<style>body{{margin:0;background:#f4f5f7;font:14px Arial,sans-serif;color:#172b4d}} .page{{max-width:1240px;margin:0 auto;padding:24px;background:#fff}} h1{{font-size:24px}}</style>
</head><body><div class="page"><h1>Confluence page (preview)</h1><p>The tool below runs the same way it will in the HTML macro.</p>
<div id="{MOUNT_ID}"></div></div>
<script src="{BUNDLE}"></script></body></html>
'''
    os.makedirs(OUT, exist_ok=True)
    for name, text in ((BUNDLE, bundle), ("confluence-macro.html", macro), ("preview.html", preview)):
        with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
            f.write(text)
    print("wrote", OUT, f"({len(bundle.encode('utf-8')) // 1024} KB bundle)")


if __name__ == "__main__":
    main()
